export const errorCodes = {
    AUTH_ERROR: 'AUTH_ERROR',
    INVALID_URL: 'INVALID_URL',
    GENERATION_ERROR: 'GENERATION_ERROR',
    NOT_FOUND: 'NOT_FOUND',
    VALIDATION_ERROR: 'VALIDATION_ERROR',
    INTERNAL_ERROR: 'INTERNAL_ERROR',
    INVALID_EMAIL: 'INVALID_EMAIL',
    DUPLICATE_EMAIL: 'DUPLICATE_EMAIL',
    MISSING_PROJECT_DETAILS: 'MISSING_PROJECT_DETAILS'
}